## Send Email
// POST http://mkss.azurewebsites.net/Services/api/email/send
POST https://mkssazurefunctions.azurewebsites.net/api/SendEmail
Content-Type: application/json

{
    "From":"mkss.dev@gmail.com",
    "To": ["muratkazanova@outlook.com"],
    "Subject":"[TEST] Tesing Azure Email Service",
    "Body": "OptionsBuilder<br/>.UseLoggerFactory(ConsoleLoggerFactory) // To log to console<br/>.EnableSensitiveDataLogging() // to show parameter values"
}